services:
  clima:
      build:
        context: .
        dockerfile: ./apps/clima/Dockerfile
        target: development
      command: npm run start:dev clima
      env_file:
        - ./apps/clima/.env
      depends_on:
        - mongo
        - mongo-express
   
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - '3000:3000'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password123@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
